### ISSUE TITLE
При создании акта сделать фототаблицу

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/mobile.forestviolate.inspector#1]
Фототаблица должна представлять собой сетку из миниатюр фотографий. шириной или высотой 3 или 4 фотки. Количество фоток должно определяться по разрешению - при больших экранах с большим разрешением - 4, для маленьких - 3.
Для каждой миниатюры можно добавить описание. В верхнем левом углу должен быть чекбокс - для перехода в режим actionmode. В режиме actionmode должна быть кнопка выделить все/снять выделение и удалить выбранное. В правом нижнем углу фототаблицы должна быть FAB для снятия нового фото.

Уточнения:

- [x] 1) Фотография отправляется на сервер как есть, без всяких изменений.

- [x] 2) После того, как фото добавлено к акту, если есть копия, то удалить эту копию.

- [x] 3) При сохранении фото на сервер вызывать
AttachItem("-1", "YYYYmmDD-HHMMSS", "image/jpeg", description)
где description = то что введет пользователь в описании к фото;
" -1" -- тогда идентификатор будет присвоен автоматически.

- [x] 4) В интерфейсе фототаблицы необходима возможность менять description.

- [x] 5) Миниатюры фотографий делать без полей, чтобы был виден только центр фотографии.

- [x] 6) Минимальный размер миниатюры примерно 160x160 dp. Количество миниатюр на экране по ширине должно вычисляться исходя из того, сколько поместиться минимальных миниатюр, но не более 4-х.

- [x] 7) FAB скрывать при переходе в ActionMode.

- [x] 8) При снятии галочки с последнего выделенного элемента ActionMode должен отключаться.

- [x] 9) При повторном нажатии на кнопку выделения всех элементов всё выделение должно сниматься, ActionMode должен отключаться.

- [x] 10) При удалении фотографий выводить сообщение с предупреждением в виде
android.support.design.widget.Snackbar

- [x] 11) CheckBox на фото должен быть одинаково хорошо виден и на светлом фоне, и на темном.

- [x] 12) Для FAB сделать нужную иконку и разместить в правом нижнем углу.

- [x] 13) При нажатии на фото показывать окно с фотографией на всё окно и описанием без обрезки текста внизу окна.

**Comment by simgislab** [comment]
это будет третья реализация набора фото, после метро Стаса и комьюлинка Никиты? может остановиться на чем-то одном таки?

**Comment by BishopGIS** [comment]
Нет, тут есть ряд особенностей:
1. Фототаблица это отдельный документ
2. Будет много фоток
3. Фотки должны быть с подписями
4. Нужен удобный механизм управления фотками

В общем тут стандартное не подойдет.

**Comment by simgislab** [comment]
мне кажется или это все равно вписывается достаточно в единый компонент (не уверен про 1)? 

@4eRTuk предлагал сделать внешний компонент на базе того, что в m4a, звучит логично

**Comment by BishopGIS** [comment]
Когда будет сделано - посмотрим, насколько это применимо. У нас уже есть набор абстрактных классов для поддержки всех особенностей текущей модели данных в forestinspector, которая сильно отличаетвся от НГМ (тут есть набор связанных таблиц). Кроме того имеется ряд особенностей. Например, есть часть графических файлов которые показывать нельзя - тот же файл "официальной" подписи, возможно еще что-то.
В общем сильно зависит от того как это будет сделано @4eRTuk.

**Comment by simgislab** [comment]
я не знаю делает ли он или нет

но любом случае, ожидать что он сделает что-то применимое, не рассказав ему что нужно, не стоит

**Comment by BishopGIS** [comment]
Все что нужно в НГМ от библиотеки фоток написал в соответсвующем тикете (https://github.com/nextgis/android_gisapp/issues/55). Если не то, просьба исправить. И это явно не то что нужно в данном тикете.

**Comment by simgislab** [comment]
а почему например подписи не нужны или удобное управление? не говоря уже про 2.

**Comment by BishopGIS** [comment]
Потому что, в случае генератора форм вы сами отказались от вкладок и ориентаций и много еще чего. Поэтому, при текущей логике должна быть каруселька как в clink. Иначе не понятно как это сделать в formbuilder и как на форме разместить. 
В инспекторе наоборот уже сделан специальный отдельный экран. И на полном экране правильнее и удобнее использовать подход галереи.
Да и текст в случае инспектора может быть довольно большой. Все что пишется в форме войдет в официальный акт. В NGM подход быстрого сбора и предполагается, что большие и обстоятельные подписи, какое лесонарушение, в соответсвии с какими нормативными актами не пишутся.

**Comment by simgislab** [comment]
>в случае генератора форм вы сами отказались от вкладок и ориентаций

но тут ключевое слово же - *пока*

не совсем понял как это с ФБ связано, но смотри, тебе виднее, я только о том, что у нас уже 3 версия одного и того же делается.

**Comment by BishopGIS** [comment]
В данном случае все таки это иное. В терминах FB - каруселька фоток - это контрол, а тут целый отдельный экран. И в этом основное отличие. Тут как раз наоборот можно в перспективе в FB добавить новые элементы - не контролы а целые экраны в виде вкладок.

**Comment by NikitaFeodonit** [comment]
В Компьюлинке я использовал стандартный RecyclerView для отображения списка фотографий, а оформление отдельной фотографии делал сам, так как там ничего, кроме фото ненужно было показывать.

Сдесь я также использую RecyclerView, а для оформления фото использую опять же стандартный CardView, который является контейнером для разных элементов. В него я сейчас помещаю саму фото, описание к ней и CheckBox.

Эти элементы (RecyclerView и CardView) универсальные, под конкретные условия их можно настраивать по-разному.

RecyclerView позволяет разместить элементы линейно (вертикально и горизонтально), сеткой-таблицей, или с произвольным размером элемента в таблице, как, например, [в этой статье](http://enoent.fr/blog/2015/01/18/recyclerview-basics/) видно на картинках

CardView позволяет настроить себя также очень по-разному: цвет, размер рамки вокруг своего содержимого, наличие и размер тени, закругление углов и прочее.

Так как эти элементы стандартные, то не нужно использовать дополнительные библиотеки.
