### ISSUE TITLE
Акт об обнаружении орудий заготовки не создаётся

### ISSUE THREAD

**Issue by trolleway** [nextgis/mobile.forestviolate.inspector#100]
![fw_akt_obnaruzenia_orudiy_entering](https://cloud.githubusercontent.com/assets/4630662/16564286/53a3aed0-420f-11e6-8949-f4eebb5d4b3c.png)
После нажатия кнопки Добавить выдаётся сообщение "Неверные параметры", запись в акт не добавляется.

**Comment by NikitaFeodonit** [comment]
Все поля должны быть непустыми, иначе сообщение о некорректности данных.

**Comment by BishopGIS** [comment]
Давай уберем это ограничение. Я не помню, что бы мы такое вводили.
Должно быть заполнено хотя бы одно поле.
