### ISSUE TITLE
Убрать с карты кнопку удаления дырки

### ISSUE THREAD

**Issue by trolleway** [nextgis/mobile.forestviolate.inspector#101]
В геометрии не появляется дырок, поэтому не нужна кнопка удаления дырки, а то ещё объяснять зачем она.
см. фиг. 1, кнопка №4
![fw_ngmobile_toolbar_mpolyg_pic](https://cloud.githubusercontent.com/assets/4630662/16586676/c386c316-42cf-11e6-99d2-36438b5f9b52.png)

**Comment by NikitaFeodonit** [comment]
Эта кнопка подписана как "Удалить мультиполигон". Хотя в коде она не используется вовсе.

**Comment by NikitaFeodonit** [comment]
Кнопка №2, соответственно, подписана как "Добавить мультиполигон". И эти кнопки даже внешне похожи.

**Comment by NikitaFeodonit** [comment]
Тут, скорее, нужно реализовать функционал этой кнопки, но это должен быть другой тикет.

**Comment by BishopGIS** [comment]
Да, согласен, что нужно реализовать.
