### ISSUE TITLE
Зажать нижний зум

### ISSUE THREAD

**Issue by NikitaFeodonit** [nextgis/mobile.forestviolate.inspector#108]
Подробнее тут:
https://github.com/nextgis/mobile.forestviolate.inspector/issues/107

**Comment by NikitaFeodonit** [comment]
Перепутал с user

**Comment by BishopGIS** [comment]
Что значит перепутал? Надо в карте сделать что бы ниже 19-го нельзя было зумится.

**Comment by NikitaFeodonit** [comment]
Не там тикет завел.

**Comment by BishopGIS** [comment]
Я так поимаю это касается обоих приложений. Карта то в обоих есть.
