### ISSUE TITLE
Сделать поддержку слоя лесонарушений

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/mobile.forestviolate.inspector#15]
Это точечный слой из Кедра в котором будет координаты лесонарушения и некая атрибутика.
При создании акта о лесонарушении инспектору необходимо предъявить диалог с выбором записей из этого слоя по которым формируется акт. Номер записи (некий guid) пишется в поле целеуказания акта. Если инспектор ничего не выбрал - пишется -1. В сам слой пишется новый статус (проверено)
Этот же слой должен показываться на карте. Точки должны быть разного цвета (новые точки - красным, проверенные точки - зеленым).
Возможно другие цвета - основной смысл - обеспечить инспетору возможность выбора точки для инспекции.
При клике на точку необходимо показывать ее атрибутику.

**Comment by BishopGIS** [comment]
Адрес слоя лесонарушений http://176.9.38.120/fv/resource/57
ключ: fv

**Comment by BishopGIS** [comment]
Пересекается с https://github.com/nextgis/mobile.forestviolate.inspector/issues/42 в части указания целеуказаний

**Comment by NikitaFeodonit** [comment]
Осталась только часть работы с картой.
