### ISSUE TITLE
Отключить свайп для перехода между табами

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/mobile.forestviolate.inspector#17]
Сделать настройку для отключения свайпа для перехода между табами.
Свайп может мешать скролить карту.

**Comment by NikitaFeodonit** [comment]
Я бы вовсе отключил свайп (без настройки) там, где есть карта. Свайп реально мешает скролить карту, а для переключения между вкладками есть заголовки вкладок.

**Comment by BishopGIS** [comment]
Так это уже сделано. Тогда закрываю.

**Comment by NikitaFeodonit** [comment]
При просмотре созданного акта не сделано. То есть свайп работает и мешает при просмотре карты.

Пока переоткрою.
