### ISSUE TITLE
Выделять свои документы от чужих

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/mobile.forestviolate.inspector#20]
Документы созданные инспектором должны как-то выделяться в списке - например цветом фона (аналогично - на карте). При этом следует учитывать, что у нас 2 темы приложения - светлая и темная.

Возможно протребуется переделка структуры таблиц.

**Comment by NikitaFeodonit** [comment]
> Возможно протребуется переделка структуры таблиц.

Необходимо, чтобы таблицы docs и notes содержали из таблицы inspectors поле user или login.

Сейчас в таблице docs поле user соответствует полю user_desc в таблице inspectors.

А таблица notes уже содержит поле login, которое соответствует полю login в таблице inspectors.

**Comment by BishopGIS** [comment]
В таблице notes есть цифровое поле user_id которое соответствует идентификатору записи в таблице inspectors (id).
Предлагаю добавить такое же поле и в таблицу docs.
по цифровому полю и сравнивать быстрее и этот идентификатор точно не поменяется (в отличие от логина и имени пользователя) он уникален.

**Comment by NikitaFeodonit** [comment]
Если id уникален, то пусть будет он.

**Comment by NikitaFeodonit** [comment]
Осталась только часть работы с картой.
