### ISSUE TITLE
Ошибки темной темы

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/mobile.forestviolate.inspector#39]
1. В фототаблице чекбокс белый, рамка белая, текст введенный белый на белом.
2. В Actionmode иконки должны быть белыми.
![screenshot_2015-11-19-22-59-55](https://cloud.githubusercontent.com/assets/1708122/11283177/7b47deba-8f14-11e5-9e3d-4acf55850bee.png)
![screenshot_2015-11-19-23-00-09](https://cloud.githubusercontent.com/assets/1708122/11283178/7b4903a8-8f14-11e5-88fa-8d3fec1cd02b.png)
![screenshot_2015-11-19-23-00-40](https://cloud.githubusercontent.com/assets/1708122/11283180/7b4aa74e-8f14-11e5-83a3-88e3cfe9fb71.png)

**Comment by NikitaFeodonit** [comment]
Иконки сейчас задаются подобным образом
        android:icon="?attr/ic_action_delete_inverse"
А значение ic_action_delete_inverse задается темой в maplibui.

Для исправления нужно или в maplibui сделать изменение, но тогда это будет влиять на все проекты. Или только в приложении через замену на
        android:icon="@drawable/ic_action_delete_dark"

Как делать?

**Comment by NikitaFeodonit** [comment]
В мобильном в списке треков сейчас часть иконок белые, а часть черные.

**Comment by NikitaFeodonit** [comment]
В мобильном задается так:
        android:icon="@drawable/ic_action_visibility_on_dark"
        android:icon="@drawable/ic_action_visibility_off_dark"
        android:icon="?attr/ic_action_delete_inverse"
        android:icon="?attr/ic_action_content_select_all_inverse"
по этому часть так, а часть иначе.

Делаю через замену в приложении. И мобильное поправлю.

**Comment by BishopGIS** [comment]
У нас во всех приложениях такая особенность: тулбар всегда темный и все подписи и иконки светлые (синий, зеленый, черный, серый), но меню меняется  (три точки) меняется в зависимости от темы. А вот контент окна (диалога)  может быть и темный и светлый и там иконки тоже должны меняться в зависимости от темы. 
Поэтому надо все это учитывать и не смешивать. У нас есть свои белые иконки для ActionMode - раньше они были жестко прописаны - может кто поменял?

**Comment by NikitaFeodonit** [comment]
Я так понял: в стилях maplibui есть ссылки на иконки, которые то темные, то светлые. И если нужно при смене темы смена и типа иконок, то используем для конкретного элемента ссылку (для меню, для элемента списка и т.п.). А если смена типа иконки не нужна, то используем прямое указание файла иконки. Что я и сделал для ActionMode, поправив на такое:
android:icon="@drawable/ic_action_delete_dark"
android:icon="@drawable/ic_action_content_select_all_dark"

А вопросы задавал, пока не вник до конца.

**Comment by BishopGIS** [comment]
Да, все верно.
