### ISSUE TITLE
При создании всех документов кроме заметок выводить диалог выбора целеуказаний

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/mobile.forestviolate.inspector#42]
- [x] создать слой с целеуказаниями
- [x] выбирать из слоя по bbox
- [x] показывать диалог и брать из него идентификатор или ставить -1 (радиокнопки)

**Comment by BishopGIS** [comment]
Слой создан и он автоматические (раз в сутки) обновляется из кедра.
Ключ: fv
Ресурс http://176.9.38.120/fv/resource/57

**Comment by NikitaFeodonit** [comment]
Эта часть работы с целеуказаниями сделана. Закрываю.
