### ISSUE TITLE
В момент изменения темы тема настроек не меняется, пока их не закрыть и открыть заново.

### ISSUE THREAD

**Issue by NikitaFeodonit** [nextgis/mobile.forestviolate.inspector#46]

**Comment by BishopGIS** [comment]
Я бы не стал называть это багом и бороться с  этим.

**Comment by NikitaFeodonit** [comment]
В мобильном уже это сделано. Можно просто перенести, как думаю.

**Comment by BishopGIS** [comment]
У нас вроде не было этого в NextGIS Mobile или ты не об этом?

**Comment by NikitaFeodonit** [comment]
Да, я о NextGIS Mobile. Сейчас уже работает так:
Меню -- Настройки -- Общие -- Тема -- переключить тему
В момент переключения темы активити настроек просто закрывается и открывается заново, как я вижу.

Для пользователя так понятнее, что происходит. А раз увидел в мобильном, то решил и тут заметку сделать. Думаю, там несложно будет перенести.
