### ISSUE TITLE
При заполнении фототаблицы теряются данные в документе

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/mobile.forestviolate.inspector#52]
Цитата из отчета по тестированию "при заполнении п.п.1-9 Акта о лесонарушении переходим к функции «заполнить фототаблицу». После добавления фотографий возвращаемся в меню акт о лесонарушении, в котором в пунктах с 1 по 9 все ранее записанные текстовые сведения отсутствуют. Приходится повторно заполнять все пункты акта о лесонарушении"

**Comment by NikitaFeodonit** [comment]
Проблема в сохранении состояния. У меня не проявляется, так как достаточно памяти на устройстве. Если памяти мало, то при загрузке приложения для фотографирования наше приложение выгружается, без сохранения полей.

Как вариант -- сохранять временные Features и слои в базе maplib, для чего в maplib сделать функционал для работы с такими временными объектами.
