### ISSUE TITLE
В форме заполнения акта оставить п.3 пустым

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/mobile.forestviolate.inspector#55]
3. Ответственность за лесонарушение определяется по факту рассмотрения полученных материалов и их проверке. 

```
пункт в бланке оставить но не заполняется​
```

**Comment by NikitaFeodonit** [comment]
Не понял, что должно быть. При создании акта пункт 3 звучит так:
"3. Когда и кем обнаружено лесонарушение"

А в 1-м пункте есть EditText, который по-умолчанию заполнен таким текстом:
"Ответственность за данное лесонарушение предусмотрена ст. 269 УКРФ"

То есть о каком 3-м пункте идет речь и где должна быть ожидаемая строка?

**Comment by BishopGIS** [comment]
Вот то что там заполнено "Ответственность за данное лесонарушение предусмотрена ст. 269 УКРФ" - не должно быть. Т.е. просто пустая строка.
