### ISSUE TITLE
Из слоя fv "Точки лесонарушений" загружать записи только за последние полгода

### ISSUE THREAD

**Issue by NikitaFeodonit** [nextgis/mobile.forestviolate.inspector#71]
Необходимо добавить фильтрацию по дате за последние полгода, но пока это не сделано в API сервера:
&date>""

Должно быть так:
ngwVectorLayer.setServerWhere(
String.format(Locale.US, "bbox=%f,%f,%f,%f&status='Новое лесоизменение'&date>'DATE'", minX, minY, maxX, maxY));

**Comment by BishopGIS** [comment]
АПИ сервера готово: nextgis/nextgisweb_forest_violations#18
