### ISSUE TITLE
Переделать способ ввода пней

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/mobile.forestviolate.inspector#75]
В полевых условиях оказалось неудобно вводить пни через диалог.
Заказчик просит сделать табличку.
Итого вместо диалога ввода нужно сделать activity.
В верхней части шапка с контролами:

* разряд высот (выпадающий список)
* категория (по умолчанию деловая)
* выдел (текстовое поле)

Далее табличка. Колонки - породы деревьев, первая строка - диаметр пня.
Внутри каждой ячейки цифра в статике (0) по-умолчанию и 3 кнопки "+", "-" и задать вруучную (или не кнопка, а клик по цифре показывает диалог ввода цифры. Кнопки соответсвенно увеличивают или уменьшают цифру.

Заголовки колонок и первый столбец должны быть закреплены и не скрываться при скроле.

После сохранения табличка расшивается по цифрам больше 0 в список который сейчас сдела в ведомости.
При клике на элемент списка уже открывается тот диалог, который и сейчас открывается (т.е. этот функционал убирать не надо).

Меньше 8 дюймовых планшетов не будет, так что под малые экраны подстраиваться не надо.

**Comment by NikitaFeodonit** [comment]
Сделано.
