### ISSUE TITLE
Документ не выбран

### ISSUE THREAD

**Issue by drnextgis** [nextgis/mobile.forestviolate.inspector#84]
1. Нажимаем на FAB и выбираем, например, `Акт о лесонарушении`
2. Ничего не заполняем и нажимаем `Назад`
3. Запись появляется в списке документов. Так и должно, мы же её не сохраняли?
4. Как продолжить её редактирование? Если на неё нажать то получаем `Документ не выбран`.
5. Может её как-то можно удалить?

**Comment by NikitaFeodonit** [comment]
Нет, так быть не должно.
