### ISSUE TITLE
На экране создания геометрии вручную 2 нижние панели накладываются

### ISSUE THREAD

**Issue by trolleway** [nextgis/mobile.forestviolate.inspector#99]
Создание акта - ввод геометрии вручную

![screenshot_2016-07-04-14-55-38](https://cloud.githubusercontent.com/assets/4630662/16558384/07382a60-41ee-11e6-84f3-37af94fa3459.png)

**Comment by NikitaFeodonit** [comment]
Какое поведение ожидается с этими панелями в этом случае?

**Comment by BishopGIS** [comment]
Я думаю проще сделать скрытие информационной панели, а при выходе из режима редактирования опять показ. Такое было раньше в основном мобильном. Если есть другие идеи - пиши.
